slopBed -i AA1.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA1.peaks.500bp.hg38.bed
slopBed -i AA2.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA2.peaks.500bp.hg38.bed
slopBed -i AA3.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA3.peaks.500bp.hg38.bed
slopBed -i AA4.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA4.peaks.500bp.hg38.bed
slopBed -i AA4a.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA4a.peaks.500bp.hg38.bed
slopBed -i AA4b.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AA4b.peaks.500bp.hg38.bed
slopBed -i AB1.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AB1.peaks.500bp.hg38.bed
slopBed -i AC.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AC.peaks.500bp.hg38.bed
slopBed -i AN.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/AN.peaks.500bp.hg38.bed
slopBed -i CL4.peaks.bed -g /data/RDCO/genomes/hg38/genome.fa.fai  -pct -b -0.5 |slopBed -b 250 -g /data/RDCO/genomes/hg38/genome.fa.fai -i - |sort -k1,1 -k2n,2n >central/CL4.peaks.500bp.hg38.bed
