#!/usr/bin/perl
use strict;
use Bio::SeqIO;

my %stat;
my $prdm9A = 'TGTGGACAAGGTTTCAGTGTTAAATCAGATGTTATTACACACCAAAGGACACATACAGGGGAGAAGCTCTACGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCTGGAAGTCACACCTCCTCATTCACCAGAGGATACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCTGGCAGTCAGTCCTCCTCACTCACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCCGGCAGTCAGTCCTCCTCACTCACCAGAGGAGACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCCGGCAGTCAGTCCTCCTCACTCACCAGAGGAGACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCTGGCAGTCAGTCCTCCTCAGTCACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCTGGCAGTCAGTCCTCCTCACTCACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCAATAAGTCACACCTCCTCAGACACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTCGCGATAAGTCACACCTCCTCAGACACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGAGATAAGTCAAACCTCCTCAGTCACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCAATAAGTCACACCTCCTCAGACACCAGAGGACACACACAGGGGAGAAGCCCTATGTCTGCAGGGAGTGTGGGCGGGGCTTTCGCAATAAGTCACACCTCCTCAGACACCAGAGGACACACACAGGGGAGAAGCCCTACGTCTGCAGGGAGTGTGGGCGGGGCTTTAGCGATAGGTCAAGCCTCTGCTATCACCAGAGGACACACACAGGGGAGAAGCCCTACGTCTGCAGGGAG';

my @ref = split(//,$prdm9A);

my $fa = Bio::SeqIO->new(-file => $ARGV[0], -format => 'fasta');

while (my $s = $fa->next_seq){
  my @seq = split(//,uc($s->seq));
  for my $i(0..$#ref){
    if ($ref[$i] eq $seq[$i]){
      $stat{all}->{OK}++;
      $stat{$ref[$i]}->{OK}++;
    }else{
      $stat{all}->{BAD}++;
      $stat{$ref[$i]}->{BAD}++;
    }
    if ($i > 0 && $i < $#ref){
      if (join("",@ref[$i-1..$i+1]) eq join("",@seq[$i-1..$i+1])){
        $stat{join("",@ref[$i-1..$i+1])}->{OK}++;
      }else{
        $stat{all}->{BAD}++;
        $stat{join("",@ref[$i-1..$i+1])}->{BAD}++;
      }
    }
  }
}

print join ("\t",'type','good','bad','total','pc')."\n";
for my $k(sort {$a cmp $b} keys %stat){
  my $pcOK = sprintf('%4.2f',$stat{$k}->{OK}/($stat{$k}->{OK} +  $stat{$k}->{BAD}));
  print join ("\t",$k, $stat{$k}->{OK}, $stat{$k}->{BAD},  $stat{$k}->{OK} +  $stat{$k}->{BAD},$pcOK)."\n";
}
